url: "https://citharus.github.io"
baseurl: "citharus.github.com"
title: ""
description: ""

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

plugins:
  - jekyll-postcss
  - jekyll-seo-tag

sass:
  load_paths:
    - _sass
    - node_modules

postcss:
  cache: false
